[project]
name = "figure-friday"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "glicko2>=2.1.0",
    "numpy>=2.3.3",
    "plotly>=6.3.0",
    "polars>=1.33.1",
]
